# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2021-03-01 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonCalls',
            fields=[
                ('user', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fat_count', models.IntegerField(default=0)),
                ('dumb_count', models.IntegerField(default=0)),
                ('stupid_count', models.IntegerField(default=0)),
            ],
        ),
    ]
